config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :welcome
  resources :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)

    if @picture.save
      redirect_to welcome_path
    else
      render :new
    end
  end

  private
  def picture_params
    params.require(:picture).permit(:title, :content)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="simple-title">
  <h1>About</h1>
</div>

app/views/common/_header.html.erb
<p class="navMenu">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Images', root_path %>
  <%= link_to 'About', about_index_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/header' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="title">
  <h1>Welcome!</h1>
  <p>
    <button class="btn btn-success"><%= link_to "NEW POST", new_welcome_path %></button>
    <!--<button id="greet-user-button" class="btn btn-success">Click me!</button>-->
  </p>
</div>

<div class="pictureBlock">
  <p>
    <% @pictures.each do |picture| %>
      <li>
        <b><%= picture.title %></b><br>
          <%= picture.content %><br>
      </li><br>
    <% end %>
  </p>
</div>

<%= javascript_pack_tag 'hello' %>

app/views/welcome/new.html.erb
<h1><b>New post</b></h1>
<%= form_for :picture do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit "SAVE" %>
  </div>
<% end %>

app/views/welcome/show.html.erb
<h1><b><%= @picture.title %></b></h1>
<p><%= @picture.content %></p>